### ISSUE TITLE
Unable to form agreements for policy case after anax restarts

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1678]
Register a node with a node policy. Agreement will form. Kill anax and bring it up again. Run `hzn agreement cancel -a`, then no new agreements will be made. The event log has the following errors:
````
  "2020-04-23 13:19:29:   Node received Proposal message using agreement 90978525c9db29e76e13a088d126f0cfb3351c608d240eab350f03773016a56b for service e2edev@somecomp.com/https://bluehorizon.network/services/location from the agbot IBM/ag12345.",
  "2020-04-23 13:19:29:   Error handling proposal for service e2edev@somecomp.com/https://bluehorizon.network/services/location. Error: Respond to proposal with error: Protocol Basic decide on proposal received error saving agreement count: Input policy is nil, agreement: 90978525c9db29e76e13a088d126f0cfb3351c608d240eab350f03773016a56b"
````

**Comment by dabooz** [comment]
I have tracked down a very similar problem in the exchange, where it stops returning nodes when the node's last agreement is cancelled. https://github.com/open-horizon/exchange-api/issues/345

**Comment by dabooz** [comment]
After fixing the problem in the exchange, the agbot is exposed to the possibility that it finds out about the agreement cancellation AFTER the policy search function has already seen the node and rejected it because it already has an agreement, but it's an agreement that is about to be cancelled. After cancelling the agreement, no more node state changes occur, so the node is never picked up by the policy search, leaving the node without an agreement.

**Comment by dabooz** [comment]
Agbot code is fixed, just waiting on the final exchange version so I can update the agbot version dependency.

**Comment by linggao** [comment]
I tested this PR and the problem still occurs. horizon version "2.26.5",  "exchange_version": "2.23.0",
